sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 192.168.89.134
    port: 3306
    database: sky_take_out
    username: remote_user
    password: your_password
  alioss:
    endpoint:
    access-key-id:
    access-key-secret:
    bucket-name:
  redis:
    host: 192.168.89.134
    port: 6379
    database: 0
  wechat:
    appid: wxd3eb207648fb77c3
    secret: 3e3694fac1e1ce5a2ab7735de064ab1c